# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
version: '2.1'
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    env_file: cred.env
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/david/txm/config:/config
      - /home/david/txm/downloads:/downloads
      - /home/david/txm/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/david/vpn/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
  nginx:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file: cred.env
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - VALIDATION=http
    volumes:
      - /home/david/web:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
