---
name: linters
'on': [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: docker-compose.yml .github/workflows/*.yml
