# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: linters
'on': push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v5
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./*.yml .github/*.yml .github/workflows/*.yml
